# This file prevents yarn from being used in this project
# Our project uses pnpm exclusively

# This will cause yarn to fail immediately
nodeLinker: 'pnpm'
yarnPath: '.yarn/releases/do-not-use-yarn'
